set fileencodings=utf8,cp1251

set undofile

set tabstop=4 softtabstop=0 expandtab shiftwidth=4 smarttab

" Search
set hlsearch
set ignorecase
set smartcase

" Terminal
if has('unix')
    set clipboard=unnamedplus
else
    set clipboard=unnamed
endif
set termguicolors
set lazyredraw
set ttyfast


" Mappings
imap fj <Esc>
nnoremap <C-s> :w<CR>
" Russian mapping
set langmap=ёйцукенгшщзхъфывапролджэячсмитьбюЁЙЦУКЕНГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮ;`qwertyuiop[]asdfghjkl\\;'zxcvbnm\\,.~QWERTYUIOP{}ASDFGHJKL:\\"ZXCVBNM<>
imap ао fj


" Plugins
" To install vim-plug:
"   curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
"   https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
call plug#begin('~/.config/vim/plugged')

Plug 'jiangmiao/auto-pairs'
Plug 'justinmk/vim-sneak'
Plug 'ntpeters/vim-better-whitespace'
Plug 'sheerun/vim-polyglot'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-surround'
Plug 'vim-airline/vim-airline'

call plug#end()

